# **SECOM Data Analysis and Model Training**

## **0. Data Download and Extraction**

The following cell downloads and extracts the data in case it is not already present in the local directory.

In [1]:
from get_data import download_and_extract_data

url = "https://archive.ics.uci.edu/static/public/179/secom.zip"
download_and_extract_data(url)

2026-01-16 18:42:50,649 - get_data - INFO - SECOM data found.
2026-01-16 18:42:50,650 - get_data - INFO - Data ready to be used.


## **1. Exploratory Data Analysis**

### **1.1 Analysis of Sensor Data**

#### **Load data**

In [2]:
import pandas as pd

In [3]:
data_path = r"data\secom.data"
df = pd.read_csv(data_path, sep=" ", header=None)

#### **Overview of data**

In [4]:
df.shape

(1567, 590)

In [5]:
df.head(5)

0        1          2          3       4      5         6       7    \
0  3030.93  2564.00  2187.7333  1411.1265  1.3602  100.0   97.6133  0.1242   
1  3095.78  2465.14  2230.4222  1463.6606  0.8294  100.0  102.3433  0.1247   
2  2932.61  2559.94  2186.4111  1698.0172  1.5102  100.0   95.4878  0.1241   
3  2988.72  2479.90  2199.0333   909.7926  1.3204  100.0  104.2367  0.1217   
4  3032.24  2502.87  2233.3667  1326.5200  1.5334  100.0  100.3967  0.1235   

      8       9    ...     580       581     582     583     584      585  \
0  1.5005  0.0162  ...     NaN       NaN  0.5005  0.0118  0.0035   2.3630   
1  1.4966 -0.0005  ...  0.0060  208.2045  0.5019  0.0223  0.0055   4.4447   
2  1.4436  0.0041  ...  0.0148   82.8602  0.4958  0.0157  0.0039   3.1745   
3  1.4882 -0.0124  ...  0.0044   73.8432  0.4990  0.0103  0.0025   2.0544   
4  1.5031 -0.0031  ...     NaN       NaN  0.4800  0.4766  0.1045  99.3032   

      586     587     588       589  
0     NaN     NaN     NaN       NaN  
1  0.0096  0.0201  0.0060  208.2045  
2  0.0584  0.0484  0.0148   82.8602  
3  0.0202  0.0149  0.0044   73.8432  
4  0.0202  0.0149  0.0044   73.8432  

[5 rows x 590 columns]

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1567 entries, 0 to 1566
Columns: 590 entries, 0 to 589
dtypes: float64(590)
memory usage: 7.1 MB


All columns contain data of type float64, which means there are no categorical variables in the dataset.

#### **Check for constant features and drop them**

In [7]:
constant_features_mask = df.nunique(dropna=True) <= 1
print(f"{sum(constant_features_mask)} columns contain constant values. They are removed.")
constant_features = df.columns[constant_features_mask]
constant_features.to_numpy()

116 columns contain constant values. They are removed.


array([  5,  13,  42,  49,  52,  69,  97, 141, 149, 178, 179, 186, 189,
       190, 191, 192, 193, 194, 226, 229, 230, 231, 232, 233, 234, 235,
       236, 237, 240, 241, 242, 243, 256, 257, 258, 259, 260, 261, 262,
       263, 264, 265, 266, 276, 284, 313, 314, 315, 322, 325, 326, 327,
       328, 329, 330, 364, 369, 370, 371, 372, 373, 374, 375, 378, 379,
       380, 381, 394, 395, 396, 397, 398, 399, 400, 401, 402, 403, 404,
       414, 422, 449, 450, 451, 458, 461, 462, 463, 464, 465, 466, 481,
       498, 501, 502, 503, 504, 505, 506, 507, 508, 509, 512, 513, 514,
       515, 528, 529, 530, 531, 532, 533, 534, 535, 536, 537, 538])

In [8]:
df = df.loc[:, ~constant_features_mask]

In [9]:
df.shape

(1567, 474)

#### **Analysis and handling of missing values by column**

In [10]:
print("Statistics on numbers of missing values per column:")
df.isna().sum(axis=0).describe()

Statistics on numbers of missing values per column:


count     474.000000
mean       86.784810
std       267.540335
min         0.000000
25%         1.000000
50%         4.000000
75%        10.000000
max      1429.000000
dtype: float64

On average, each column has about 87 missing values, while the highest number of missing values is 1429 (out of 1567 records).

In [11]:
top_na_cols = 50
print(f"{top_na_cols} columns with most missing values:")
top_na_cols_df = df.isna().sum().sort_values(ascending=False)[:top_na_cols].to_frame().reset_index()
top_na_cols_df.columns = ["Col number", "Num NAs"]
top_na_cols_df

50 columns with most missing values:


Col number  Num NAs
0          157     1429
1          292     1429
2          293     1429
3          158     1429
4           85     1341
5          358     1341
6          220     1341
7          492     1341
8          516     1018
9          110     1018
10         384     1018
11         382     1018
12         383     1018
13         111     1018
14         246     1018
15         245     1018
16         244     1018
17         109     1018
18         517     1018
19         518     1018
20         581      949
21         578      949
22         579      949
23         580      949
24         346      794
25          73      794
26         345      794
27          72      794
28         247      715
29         519      715
30         112      715
31         385      715
32         569      273
33         568      273
34         567      273
35         565      273
36         566      273
37         562      273
38         564      273
39         563      273
40         553      260
41         551      260
42         552      260
43         548      260
44         557      260
45         549      260
46         550      260
47         547      260
48         546      260
49         556      260

In [12]:
na_filter_threshold = 0.2
na_filter_mask = df.isna().sum()/len(df) > na_filter_threshold
print(f"{sum(na_filter_mask)} columns have more than {na_filter_threshold:.0%} missing values. These columns are dropped.")
df = df.loc[:, ~na_filter_mask]

32 columns have more than 20% missing values. These columns are dropped.


In [13]:
df.shape

(1567, 442)

#### **Analysis and handling of missing values by row**

In [14]:
print("Statistics on numbers of missing values per row:")
df.isna().sum(axis=1).describe()

Statistics on numbers of missing values per row:


count    1567.000000
mean        5.110402
std         9.455546
min         0.000000
25%         0.000000
50%         0.000000
75%         8.000000
max        99.000000
dtype: float64

In [15]:
top_na_rows = 20
print(f"{top_na_rows} rows with most missing values:")
top_na_rows_df = df.isna().sum(axis=1).sort_values(ascending=False)[:top_na_rows].to_frame().reset_index()
top_na_rows_df.columns = ["Row number", "Num NAs"]
top_na_rows_df

20 rows with most missing values:


Row number  Num NAs
0         1566       99
1         1564       99
2         1561       87
3          995       74
4          846       66
5          814       66
6          512       62
7          511       60
8         1206       54
9         1234       54
10        1552       44
11        1555       44
12        1556       44
13        1554       44
14        1547       44
15        1551       44
16        1565       44
17        1560       44
18         336       44
19         752       44

In [16]:
max_na_count = (df.isna().sum(axis=1)).max()
max_na_fraction = max_na_count/df.shape[1]
print(f"The rows with the most missing values have at most {max_na_fraction:.0%} missing values.\nNo rows will be removed due to missing values.")

The rows with the most missing values have at most 22% missing values.
No rows will be removed due to missing values.


### **1.2 Analysis of Labels**

In [17]:
labels_path = r"data\secom_labels.data"
labels_df = pd.read_csv(labels_path, sep=" ", header=None)

In [18]:
labels_df.shape

(1567, 2)

In [19]:
labels_df.head(5)

0                    1
0 -1  19/07/2008 11:55:00
1 -1  19/07/2008 12:32:00
2  1  19/07/2008 13:17:00
3 -1  19/07/2008 14:43:00
4 -1  19/07/2008 15:22:00

In [20]:
labels_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1567 entries, 0 to 1566
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   0       1567 non-null   int64 
 1   1       1567 non-null   object
dtypes: int64(1), object(1)
memory usage: 24.6+ KB


The labels contain no missing values.

In [21]:
labels_df[0].value_counts()

0
-1    1463
 1     104
Name: count, dtype: int64

In [22]:
labels_df[0].value_counts(normalize=True)

0
-1    0.933631
 1    0.066369
Name: proportion, dtype: float64

As mentioned in the dataset description, there are 104 test fails (which amount to 6.6% of tests), while all the other tests passed.

## **2. Feature Selection**

## **2.1 Correlation Analysis**

The correlation between the features will be computed, with the aim of dropping features that are highly correlated with others. This will help reduce the number of features and thereby reduce the time needed to test models in the next step.

In [27]:
import numpy as np

In [28]:
corr = df.corr().abs()
corr.shape

(442, 442)

In [29]:
upper = corr.where(np.triu(np.ones(corr.shape), k=1).astype(bool))

correlated_pairs = (
    upper.stack()
    .reset_index()
    .rename(columns={
        "level_0": "feature_1",
        "level_1": "feature_2",
        0: "feature_corr"
    })
)

In [30]:
# Threshold for deciding which features are considered highly correlated:
corr_threshold = 0.9

In [33]:
correlated_pairs = correlated_pairs[
    correlated_pairs["feature_corr"] >= corr_threshold
]
n_correlated_feat = len(correlated_pairs)
print(f"{n_correlated_feat} pairs of features are highly correlated (>= {corr_threshold:.2f}).")
correlated_pairs

349 pairs of features are highly correlated (>= 0.90).


feature_1  feature_2  feature_corr  target_corr_f1  target_corr_f2  \
1759           4          7      0.916410        0.013760        0.012993   
1879           4        140      0.999975        0.013760        0.013618   
1971           4        275      0.999976        0.013760        0.013621   
2065           4        413      0.938416        0.013760        0.006381   
2750           7        140      0.916715        0.012993        0.013618   
...          ...        ...           ...             ...             ...   
97407        575        577      0.928311        0.052731        0.049633   
97440        583        584      0.994771        0.005981        0.005419   
97441        583        585      0.999890        0.005981        0.005034   
97446        584        585      0.995342        0.005419        0.005034   
97458        587        588      0.974276        0.035392        0.031168   

       drop  
1759      7  
1879    140  
1971    275  
2065    413  
2750      7  
...     ...  
97407   577  
97440   584  
97441   585  
97446   585  
97458   588  

[349 rows x 6 columns]

For each pair of highly correlated features, identify the one that has the lowest correlation with the target variable. It will be dropped.

In [34]:
target_corr = df.apply(lambda col: col.corr(labels_df[0])).abs()

correlated_pairs["target_corr_f1"] = correlated_pairs["feature_1"].map(target_corr)
correlated_pairs["target_corr_f2"] = correlated_pairs["feature_2"].map(target_corr)

correlated_pairs["feature to drop"] = np.where(
    correlated_pairs["target_corr_f1"] < correlated_pairs["target_corr_f2"],
    correlated_pairs["feature_1"],
    correlated_pairs["feature_2"]
)
correlated_pairs

feature_1  feature_2  feature_corr  target_corr_f1  target_corr_f2  \
1759           4          7      0.916410        0.013760        0.012993   
1879           4        140      0.999975        0.013760        0.013618   
1971           4        275      0.999976        0.013760        0.013621   
2065           4        413      0.938416        0.013760        0.006381   
2750           7        140      0.916715        0.012993        0.013618   
...          ...        ...           ...             ...             ...   
97407        575        577      0.928311        0.052731        0.049633   
97440        583        584      0.994771        0.005981        0.005419   
97441        583        585      0.999890        0.005981        0.005034   
97446        584        585      0.995342        0.005419        0.005034   
97458        587        588      0.974276        0.035392        0.031168   

       drop  feature to drop  
1759      7                7  
1879    140              140  
1971    275              275  
2065    413              413  
2750      7                7  
...     ...              ...  
97407   577              577  
97440   584              584  
97441   585              585  
97446   585              585  
97458   588              588  

[349 rows x 7 columns]

In [35]:
features_to_drop = correlated_pairs["feature to drop"].unique()
print(f"Dropping {len(features_to_drop)} redundant features.")
df = df.drop(columns=features_to_drop)

Dropping 198 redundant features.


In [36]:
df.shape

(1567, 244)

### **2.2 Impute Missing Values**

In [44]:
from sklearn.impute import SimpleImputer

X = df.to_numpy()
imputer = SimpleImputer(strategy="median")
X = imputer.fit_transform(X)

### **2.2 Mutual Information**

In [37]:
# from sklearn.feature_selection import SelectKBest, mutual_info_classif, f_classif

# X = df.to_numpy()
# y = labels_df[0].to_numpy()

# selector = SelectKBest(score_func=f_classif, k=10)
# X_final = selector.fit_transform(X, y)

# final_features = X.columns[selector.get_support()]
# final_features

## **3. Model Training and Parameter Tuning**

### **3.1 Split Dataset**

In [38]:
from sklearn.model_selection import train_test_split

In [47]:
test_size = 0.2

y = labels_df[0].to_numpy()
X_full_train, X_test, y_full_train, y_test = train_test_split(X, y, test_size=test_size, random_state=42)
X_train, X_val, y_train, y_val = train_test_split(X_full_train, y_full_train, test_size=test_size/(1-test_size), random_state=42)

In [48]:
len(X_train) + len(X_val) + len(X_test) == len(X)

True

In [49]:
len(y_train) + len(y_val) + len(y_test) == len(y)

True

### **3.2 Train LogisticRegression Model**

In [50]:
from sklearn.linear_model import LogisticRegression

In [54]:
model = LogisticRegression(solver="liblinear", max_iter=1000)
model.fit(X_train, y_train)

LogisticRegression(max_iter=1000, solver='liblinear')

In [55]:
y_pred = model.predict(X_val)
(y_pred == y_val).mean()

np.float64(0.8789808917197452)

In [ ]:
# TODO: optional: view module 4 videos again
# TODO: Look into F1 score
# TODO: consider whether to rewatch module 6 videos before selecting models to test
# TODO: consider applying scaling to features (check if necessary)